apiVersion: v2
name: forms-flow-admin
description: forms-flow-admin is a component for managing apis provided by formsflow.
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
version: v9.0.0
type: application
appVersion: "9.0.0"
dependencies:
- name: formsflow
  repository: oci://registry-1.docker.io/amalsomanaot
  version: 1.x.x
