{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "formsflow.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "formsflow.names.namespace" . | quote }}
  labels: {{- include "formsflow.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-data-layer
  {{- if or .Values.annotations .Values.commonAnnotations }}
  annotations: {{- include "formsflow.tplvalues.merge" (dict "values" (list .Values.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:

{{- end }}