apiVersion: v2
name: forms-flow-mongodb
description: MongoDB(™) is an open source, document-oriented database management system. It is often referred to as a NoSQL database since it does not use SQL as the query language and instead uses JSON-like documents with dynamic schemas.
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
version: v9.0.0
type: application
appVersion: "9.0.0"
dependencies:
- name: formsflow
  repository: oci://registry-1.docker.io/amalsomanaot
  version: 1.x.x