apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-auth" (include "formsflow.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "formsflow.names.namespace" . | quote }}
  labels: {{- include "formsflow.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "formsflow.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}